server:
  port: 8080
  servlet:
    context-path: /
spring:
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/hlyy
    username: root
    password: root
  #redis:
   # host: localhost
  #  port: 6379
  #  connect-timeout: 3000
  #  database: 0
  #  password: myredis
  cache:
    type: redis
mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  type-aliases-package: com.example.model
  mapper-locations: classpath:com/example/mapper/*.xml
pagehelper:
  reasonable: true

